name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: SoftUni username - niki.evgeniev
      run: echo 'niki.evgeniev'
    - name: npm install
      run: npm install
    - name: npm start App
      run: npm run start&
    - name: UNIT Testing
      run: npm run test:unit
  build_and_ui_test:
    runs-on: ubuntu-latest
    needs: build_and_unit_test
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: npm install
      run: npm install
    - name: install PW
      run: npx playwright install
    - name: npm start App
      run: npm run start&
    - name: ui Testing
      run: npm run test:ui
  deploy_on_render:
      needs: build_and_ui_test
      runs-on: ubuntu-latest
      steps:
      - name: Deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
